" ===================================================================
" Execute external scripts
" ===================================================================
execute pathogen#infect()

" vim:textwidth=70 expandtab shiftwidth=2 tabstop=2 comments=\:\"
