#!/bin/bash
# public aliases
alias cls='cd; clear'
alias conv1000='convert -resize 1000'
alias cp='cp -i'
alias datesync='sudo ntpdate pool.ntp.org'
# dircolors sets up the 'dir' alias now
alias cgrep='grep --color=yes'
alias cegrep='egrep --color=yes'
alias grep='grep --color=auto'
alias lessr='less -R'
alias mv='mv -i'
# reload bash into the current shell after making changes to environment
alias reexec='exec -l bash'
alias rm='rm -i'
# convert epoch time to a normal date/time
alias ilf='perl -MPOSIX -pe "s/(\d+)/strftime(\"%b %d %H:%M:%S\",
    localtime(\$1))/e"'

#if [ $KERNEL_NAME = "Linux" -o $KERNEL_NAME = "SunOS" ]; then
#   alias cls='cd; clear'
#else
   # MinGW/MSYS shell
#   alias cls='cd; clsb'
#   alias clear='clsb'
#fi

# vim: set filetype=sh shiftwidth=4 tabstop=4:
# fin!
