#!/bin/bash

# environment variables for the product of crosstool-ng
ADDITIONAL_PATHS="
    /home/cross/armv6-lack_rpi-linux-gnueabi/bin
    /home/cross/powerpc-lack-linux-gnu/bin
" # ADDITIONAL_PATHS
for ADDPATH in $(echo ${ADDITIONAL_PATHS});
do
    if [ $(echo ${PATH} | grep -c ${ADDPATH}) -eq 0 ]; then
        PATH=${ADDPATH}:$PATH
    #else
    #    echo "Path: $ADDPATH already exists in \$PATH"
    fi
done

unset ADDITIONAL_PATHS ADDPATH
export PATH

# vi: set filetype=sh shiftwidth=4 tabstop=4
# fin!
