#!/bin/bash

# environment variables for the product of crosstool-ng
ADDITIONAL_PATHS="
    /home/cross/armv6-lack_rpi-linux-gnueabi/bin
    /home/cross/powerpc-lack-linux-gnu/bin
" # ADDITIONAL_PATHS
for ADDPATH in $(echo ${ADDITIONAL_PATHS});
do
    if [ $(echo ${PATH} | grep -c ${ADDPATH}) -eq 0 ]; then
        PATH=${ADDPATH}:$PATH
    #else
    #    echo "Path: $ADDPATH already exists in \$PATH"
    fi
done

CT_ARM_TUPLE="armv6-lack_rpi-linux-gnueabi"
CT_ARM_ROOT="/home/cross/${CT_ARM_TUPLE}"
CT_PPC_TUPLE="powerpc-lack-linux-gnu"
CT_PPC_ROOT="/home/cross/${CT_PPC_TUPLE}"

function armldd () {
    if [ -n $1 ]; then
        ${CT_ARM_ROOT}/bin/${CT_ARM_TUPLE}-ldd --root ${CT_ARM_ROOT} $1
    else
        "armldd: need a file to compute shared library dependencies for"
    fi
}

function ppcldd () {
    if [ -n $1 ]; then
        ${CT_PPC_ROOT}/bin/${CT_PPC_TUPLE}-ldd --root ${CT_ARM_ROOT} $1
    else
        "ppcldd: need a file to compute shared library dependencies for"
    fi
}

unset ADDITIONAL_PATHS ADDPATH
export PATH

# vi: set filetype=sh shiftwidth=4 tabstop=4
# fin!
