#!/bin/bash

# environment variables for the product of crosstool-ng
ADDITIONAL_PATHS="/opt/cross/armv6-lack_rpi-linux-gnueabi/bin"
for ADDPATH in $(echo ${ADDITIONAL_PATHS});
do
    if [ $(echo ${PATH} | grep -c ${ADDPATH}) -eq 0 ]; then
        PATH=${ADDPATH}:$PATH
    #else
    #    echo "Path: $ADDPATH already exists in \$PATH"
    fi
done

CT_ROOT="/opt/cross/armv6-lack_rpi-linux-gnueabi"

function ct-ldd () {
    if [ -n $1 ]; then
        ${CT_ROOT}/bin/armv6-lack_rpi-linux-gnueabi-ldd --root ${CT_ROOT} $1
    else
        "ct-ldd: need a file to compute shared library dependencies for"
    fi
}

unset ADDITIONAL_PATHS ADDPATH
export PATH

# vi: set filetype=sh shiftwidth=4 tabstop=4
# fin!
