#!/bin/bash

# add the user's .dir_colors directives
if [ -x /opt/local/bin/gdircolors ]; then
    alias dir='/opt/local/bin/gls --color=auto --classify'
    DIRCOLORS="/opt/local/bin/gdircolors"
    eval $($DIRCOLORS ~/.dircolors)
elif [ -x /usr/bin/dircolors ]; then
    alias dir='/bin/ls -F'
    DIRCOLORS="/usr/bin/dircolors"
    eval $($DIRCOLORS ~/.dircolors)
fi
# vi: set ft=sh sw=4 ts=4
# fin!
