#!/bin/bash

# add the user's .dir_colors directives
if [ -x /opt/local/bin/gdircolors ]; then
    # MacPorts
    alias dir='/opt/local/bin/gls --color=auto --classify'
    alias cdir='/opt/local/bin/gls --color=yes --classify'
    DIRCOLORS="/opt/local/bin/gdircolors"
    eval $($DIRCOLORS ~/.dircolors)
    return
elif [ -x /usr/local/bin/gdircolors ]; then
    # Homebrew
    alias dir='/usr/local/bin/gls --color=auto --classify'
    alias cdir='/usr/local/bin/gls --color=yes --classify'
    DIRCOLORS="/usr/local/bin/gdircolors"
    eval $($DIRCOLORS ~/.dircolors)
    return
elif [ -x /usr/bin/dircolors ]; then
    if [ $(uname -s) = "Linux" ]; then
        # GNU/Linux
        alias dir='/bin/ls --classify --color=auto'
        alias cdir='/bin/ls --color=yes --classify'
        DIRCOLORS="/usr/bin/dircolors --bourne-shell"
    elif [ $(uname -s) = "Darwin" ]; then
        # BSD/Mac OS X
        # moved this in from the 'darwin' bashrc.d file
        CLICOLOR=1
        LSCOLORS=ExFxCxDxBxegedabagacad
        export CLICOLOR LSCOLORS
        alias dir='/bin/ls -F'
        alias cdir='CLICOLOR_FORCE=1 /bin/ls -F'
        DIRCOLORS="/usr/bin/dircolors"
        eval $($DIRCOLORS ~/.dircolors)
    else
        echo "Unknown system type, unable to run 'dircolors'"
    fi
fi
# vi: set ft=sh sw=4 ts=4
# fin!
