#!/bin/bash

# shell functions
function ff {
    find . -name "*$1*" -print
} # find file from here

function find_agent {
    /usr/bin/find /tmp 2>/dev/null | grep agent
} # find a list of agent sockets on the host

function histgrep  {
    history | grep "$@" | tail -22
} # history, one screenful please

function jdate {
    echo -n "The current julian date in GMT is: "
    TZ=GMT date +%j
} # show the current Julian date in GMT time zone

# for QEMU instances
function lssh {
    /usr/bin/ssh -v -X -o "StrictHostKeyChecking no" -l $1 -p $2 localhost
} # ssh to localhost as a specific user on a specific port

function pigfind {
    if [ "x$1" != "x" ]; then
        FIND_PATH="$1"
    else
        FIND_PATH="."
    fi
    find $FIND_PATH -maxdepth 1 -type d -exec du -sh '{}' \; 2>/dev/null \
        | sort -h
} # get the sizes of the subdirectories of $PWD, sort from smallest to largest

function r97 {
    rdesktop -a 16 -g 900x700 $1 &
} # remote desktop to a host with 900x700 with 16 bit color

function ar97 {
    rdesktop -a 16 -u Administrator -g 900x700 $1 &
} # remote desktop to a host with 900x700 with 16 bit color, admin user

function ar107 {
    rdesktop -a 16 -u Administrator -g 1024x768 $1 &
} # remote desktop to a host with 900x700 with 16 bit color, admin user

function sudogrep {
    sudo grep $1 /etc/sudoers | less
} # look for the string passed in as arg 1 in the sudoers file

ctree () {
    if [ "x$1" != "x" ]; then
        tree -C "$1" | less -R
    else
        tree -C $PWD | less -R
    fi
} # show a colorized tree, and pipe to colorized less

viewjson () {
    JSON_XS_CMD=$(which json_xs)
    VIM_CMD=$(which vim)
    WGET_CMD=$(which wget)
    if [ ! -x $JSON_XS_CMD -o ! -x $VIM_CMD -o ! $WGET_CMD ]; then
        echo "ERROR: missing commands needed to run this function!"
        echo "JSON_XS_CMD: ${JSON_XS_CMD}"
        echo "VIM_CMD: ${VIM_CMD}"
        echo "WGET_CMD: ${WGET_CMD}"
        return 1
    fi
    if [ "x$1" == "x" ]; then
        echo 'Usage: viewjson "http://example.com/api/request.json"'
        echo "(Hint: quote URL to prevent shell from interpreting URL)"
        return 1
    else
        $WGET_CMD -O - "$1" | $JSON_XS_CMD | $VIM_CMD -R -c "set ft=json" -
    fi
}

# vi: set filetype=sh shiftwidth=4 tabstop=4
# конец!
