#!/bin/bash

# shell functions
function ff {
    find . -name "*$1*" -print
} # find file from here

function pigfind {
    if [ "x$1" != "x" ]; then
        FIND_PATH="$1"
    else
        FIND_PATH="."
    fi
    find $FIND_PATH -maxdepth 1 -type d -exec du -sh '{}' \; 2>/dev/null \
        | sort -h
} # get the sizes of the subdirectories of $PWD, sort from smallest to largest

function ffind {
   local START_PATH=$1
   if [ "x$START_PATH" = "x" ]; then
      find . -type f -exec ls -l '{}' \;
   else
      find $START_PATH -type f -exec ls -l '{}' \;
   fi
}

# vi: set filetype=sh shiftwidth=4 tabstop=4
# конец!
