#!/bin/bash
BREW_BIN=$(which brew)
if [ "x${BREW_BIN}" != "x" ]; then
    source $(brew --repository)/Library/Contributions/brew_bash_completion.sh
else
    echo "homebrew: 'brew' binary not installed"
fi
